### PR TITLE
[Bugfix] Fixed Wrong Principle Component Calculation

### LINKED ISSUE #2: Compression quality is noticably worse than libsquish
When testing this crate out I found it introduces significant compression artifacts that weren't present when using the c++ libsquish. I created a project demonstrating the issue [here](https://github.com/aprilwade/squish-artifacts-example). The repository includes example images for an [original image](https://raw.githubusercontent.com/aprilwade/squish-artifacts-example/main/original.png) and it after being compressed and decompressed by both [libsquish](https://raw.githubusercontent.com/aprilwade/squish-artifacts-example/main/libsquish_recompressed.png) and [squish-rs](https://raw.githubusercontent.com/aprilwade/squish-artifacts-example/main/squish-rs_recompressed.png).

### PR DESCRIPTION
**Pull request by localthomas**
The function for computing the principle component was not fully translated from the [original libsquish source](https://sourceforge.net/p/libsquish/code/HEAD/tree/trunk/maths.cpp#l235).

The indices in squish-rs are now set to the same values as libsquish.

A unit test has been added that indirectly checks this issue and should prevent any future regressions regarding this issue.
Fixes #2 .

### CODE REVIEW

**Comment by jansol** [comment]
D'oh, copy & paste bugs, my favourite. Thanks for taking the time to fish this one out!

File: squish/src/lib.rs [hunk 1]
```diff
@@ -333,4 +333,60 @@ mod tests {
...
+    #[test]
+    fn test_bc1_decompression_colour() {
+        let encoded: [u8; 8] = ENCODED_BLOCK_COLOUR_4X4;
+        let mut output_actual = [0u8; 4 * 4 * 4];
+        Format::Bc1.decompress(&encoded, 4, 4, &mut output_actual);
+        assert_eq!(output_actual, decoded_block_colour_4x4_as_rgba());
+    }
+
+    #[test]
+    fn test_bc1_compression_colour_cluster_fit() {
```
Comment (jansol) [inline squish/src/lib.rs]: Misleading function name, the test actually tries all three algorithms. Also I'd rather have it describe the particular pattern or regression it tests.

File: squish/src/lib.rs [hunk 2]
```diff
@@ -333,4 +333,60 @@ mod tests {
...
+    // the second in another and the third and last row in a third colour.
+    static DECODED_BLOCK_COLOUR_4X4: &[u8] = &[
+        255, 150, 74, 255, 150, 74, 255, 150, 74, 255, 150, 74, // row 0
+        255, 120, 52, 255, 120, 52, 255, 120, 52, 255, 120, 52, // row 1
+        255, 105, 41, 255, 105, 41, 255, 105, 41, 255, 105, 41, // row 2
+        255, 105, 41, 255, 105, 41, 255, 105, 41, 255, 105, 41, // row 3
+    ];
+
+    // BC1 data created with AMD Compressonator v4.1.5083 and is the same as libsquish
+    static ENCODED_BLOCK_COLOUR_4X4: [u8; 8] = [0xA9, 0xFC, 0x45, 0xFB, 0x00, 0xFF, 0x55, 0x55];
```
Comment (jansol) [inline squish/src/lib.rs:402]: I'm not a huge fan of having data for all tests in the same namespace like this. Also the names for the variables don't really explain what is tested with them.

**Review by jansol — COMMENTED** [review]
Some nits, not entirely sure what the best way to do scoping for the test data is. I'm working on some dependency updates & other small fixes, will merge this when I'm done.

**Comment by jansol** [comment]
Thank you! I'll try to come up with a better way to organize tests and their data later.
